# GitHub Actions workflow for Hexo CI/CD and Pages Build Deployment
# This workflow is designed to build a Hexo static site,
# report the build status, and deploy the site to GitHub Pages.

name: Hexo CI/CD

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

  pull_request:
    branches:
      - master  # Optional: run on pull requests to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      metadata: read

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Timezone set Asia/Taipei
        run: sudo timedatectl set-timezone 'Asia/Taipei'

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Compatible with your Hexo dependencies

      - name: Install dependencies
        run: yarn install  # Since your packageManager is yarn

      - name: Clean previous builds
        run: yarn clean  # Runs 'hexo clean' via yarn

      - name: Generate static files
        run: yarn build  # Runs 'hexo generate' via yarn

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./public  # Hexo generates static files in the 'public' directory

  report-build-status:
    needs: build
    runs-on: ubuntu-latest

    permissions:

    steps:

      - name: Report Build Status
        run: |
          gh api -X POST "repos/$GITHUB_REPOSITORY/pages/telemetry" \
            -F github_run_id="$GITHUB_RUN_ID" \
            -F conclusion="$CONCLUSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONCLUSION: success

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      metadata: read
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          preview: false

